# Generated by Django 3.2.7 on 2024-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='community_amenities',
            field=models.TextField(blank=True, help_text='Community amenities and nearby facilities.', verbose_name='Community Ammenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='exterior_features',
            field=models.TextField(blank=True, help_text='Exterior features and amenities.', verbose_name='Exterior Features'),
        ),
        migrations.AddField(
            model_name='property',
            name='interior_features',
            field=models.TextField(blank=True, help_text='Interior features and amenities.', verbose_name='Interior Features'),
        ),
    ]
