// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user activation
export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST"
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS"
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL"

// user reset_password
export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST"
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS"
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL"

// user reset_password_confirm
export const USER_RESET_PASSWORD_CONFIRM_REQUEST = "USER_RESET_PASSWORD_CONFIRM_REQUEST"
export const USER_RESET_PASSWORD_CONFIRM_SUCCESS = "USER_RESET_PASSWORD_CONFIRM_SUCCESS"
export const USER_RESET_PASSWORD_CONFIRM_FAIL = "USER_RESET_PASSWORD_CONFIRM_FAIL"

// Profile actions
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const LIST_AGENTS_REQUEST = "LIST_AGENTS_REQUEST";
export const LIST_AGENTS_SUCCESS = "LIST_AGENTS_SUCCESS";
export const LIST_AGENTS_FAIL = "LIST_AGENTS_FAIL";

export const LIST_TOP_AGENTS_REQUEST = "LIST_TOP_AGENTS_REQUEST";
export const LIST_TOP_AGENTS_SUCCESS = "LIST_TOP_AGENTS_SUCCESS";
export const LIST_TOP_AGENTS_FAIL = "LIST_TOP_AGENTS_FAIL";

// Property actions
export const LIST_ALL_PROPERTIES_REQUEST = "LIST_ALL_PROPERTIES_REQUEST";
export const LIST_ALL_PROPERTIES_SUCCESS = "LIST_ALL_PROPERTIES_SUCCESS";
export const LIST_ALL_PROPERTIES_FAIL = "LIST_ALL_PROPERTIES_FAIL";

export const LIST_AGENTS_PROPERTIES_REQUEST = "LIST_AGENTS_PROPERTIES_REQUEST";
export const LIST_AGENTS_PROPERTIES_SUCCESS = "LIST_AGENTS_PROPERTIES_SUCCESS";
export const LIST_AGENTS_PROPERTIES_FAIL = "LIST_AGENTS_PROPERTIES_FAIL";

export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAIL = "CREATE_PROPERTY_FAIL";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAIL = "DELETE_PROPERTY_FAIL";

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST";
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS";
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL";

export const SEARCH_PROPERTIES_REQUEST = "SEARCH_PROPERTIES_REQUEST";
export const SEARCH_PROPERTIES_SUCCESS = "SEARCH_PROPERTIES_SUCCESS";
export const SEARCH_PROPERTIES_FAIL = "SEARCH_PROPERTIES_FAIL";

export const UPLOAD_PROPERTY_IMAGE_REQUEST = "UPLOAD_PROPERTY_IMAGE_REQUEST";
export const UPLOAD_PROPERTY_IMAGE_SUCCESS = "UPLOAD_PROPERTY_IMAGE_SUCCESS";
export const UPLOAD_PROPERTY_IMAGE_FAIL = "UPLOAD_PROPERTY_IMAGE_FAIL";

