# Generated by Django 3.2.7 on 2024-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_umber',
            new_name='phone_number',
        ),
    ]
