# Generated by Django 3.2.7 on 2024-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_phone_umber_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/profile_default.jpg', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
